ldap query result must be converted to str
Traceback (most recent call last):
  File "./management/univention-directory-manager-modules/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 848, in _doit
    object.open()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1312, in open
    self._load_groups(loadGroups)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1326, in _load_groups
    primaryGroupResult = self.lo.searchDn(filter=filter_format(\'(&(cn=*)(|(objectClass=posixGroup)(objectClass=sambaGroupMapping))(gidNumber=%s))\', [primaryGroupNumber]))
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in filter_format
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in <genexpr>
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 41, in escape_filter_chars
    s = assertion_value.replace(\'\\\\\', r\'\\5c\')
TypeError: a bytes-like object is required, not \'str\'