userPassword must be checked as a string
Traceback (most recent call last):
  File "./management/univention-directory-manager-modules/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 843, in _doit
    object = univention.admin.objects.get(module, co, lo, position=\'\', dn=dn)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 108, in get
    obj = univention.admin.modules.lookup(module.module, co, lo, base=dn, superordinate=superordinate, scope=\'base\', unique=True, required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 913, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1742, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1284, in __init__
    univention.admin.handlers.simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes=attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 241, in __init__
    oldinfo = self.mapping.unmapValues(self.oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 533, in unmapValues
    info[key] = func(oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1077, in unmapDisabled
    unmapPosixDisabled(oldattr) or isPosixLocked(oldattr),
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1132, in isPosixLocked
    return userPassword and univention.admin.password.is_locked(userPassword)
  File "/usr/lib/python3/dist-packages/univention/admin/password.py", line 161, in is_locked
    match = RE_PASSWORD_SCHEME.match(password or \'\')
TypeError: cannot use a string pattern on a bytes-like object