fix issue with 29_user_uidNumber_and_group_gidNumber_collision
Traceback (most recent call last):
  File "29_user_uidNumber_and_group_gidNumber_collision", line 106, in <module>
    FAILURES = [test() for test in TESTS if test()]
  File "29_user_uidNumber_and_group_gidNumber_collision", line 106, in <listcomp>
    FAILURES = [test() for test in TESTS if test()]
  File "29_user_uidNumber_and_group_gidNumber_collision", line 47, in consecutive_user_creation
    id_to_collide_with = get_max_id()
  File "29_user_uidNumber_and_group_gidNumber_collision", line 35, in get_max_id
    users = udm_modules.lookup('users/user', None, LO, base=base_dn, scope='sub')
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 913, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1736, in lookup
    filter_str = unicode(filter_s or '')
NameError: name 'unicode' is not defined