Fix long issues
b'Traceback (most recent call last):
  File "./management/univention-directory-manager-modules/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 843, in _doit
    object = univention.admin.objects.get(module, co, lo, position=\'\', dn=dn)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 108, in get
    obj = univention.admin.modules.lookup(module.module, co, lo, base=dn, superordinate=superordinate, scope=\'base\', unique=True, required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 913, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1744, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1281, in __init__
    univention.admin.handlers.simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes=attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 242, in __init__
    oldinfo = self.mapping.unmapValues(self.oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 531, in unmapValues
    info = mapDict(self, oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 587, in mapDict
    v = mapping.unmapValue(key, value)
  File "/usr/lib/python3/dist-packages/univention/admin/mapping.py", line 525, in unmapValue
    return unmap_value(value) if unmap_value else value
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1185, in unmapWindowsFiletime
    d = long(116444736000000000)  # difference between 1601 and 1970
NameError: name \'long\' is not defined