convert bytes to string for re
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 742, in _doit
    out.extend(object_input(module, object, input, append=append))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 386, in object_input
    object[key] = value
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 448, in __setitem__
    p = s.parse(value)
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 1313, in parse
    if " " in text:
TypeError: a bytes-like object is required, not 'str'